ingress:
  - "https://arbeidsplassen.intern.dev.nav.no/personbruker"
  - "https://cv.ansatt.dev.nav.no"
next_public_environment: "dev"
pam_cv_api_audience: "dev-gcp:teampam:pam-cv-api-gcp"
pam_eures_cv_eksport_audience: "dev-gcp:teampam:pam-eures-cv-eksport"
next_public_telemetry_url: "https://telemetry.ekstern.dev.nav.no/collect"
