ingress: "https://arbeidsplassen.nav.no/personbruker"
next_public_environment: "prod"
pam_cv_api_audience: "prod-gcp:teampam:pam-cv-api-gcp"
pam_eures_cv_eksport_audience: "prod-gcp:teampam:pam-eures-cv-eksport"
next_public_telemetry_url: "https://telemetry.nav.no/collect"
