ingress:
  - "https://cv-veileder.intern.dev.nav.no/min-cv"
tenant: "trygdeetaten.no"
next_public_environment: "dev"
pam_cv_api_audience: "dev-gcp:teampam:pam-cv-api-gcp"
pam_eures_cv_eksport_audience: "dev-gcp:teampam:pam-eures-cv-eksport"
next_public_telemetry_url: "https://telemetry.ekstern.dev.nav.no/collect"
base_url: "https://www.ansatt.dev.nav.no/min-cv"
login_url: "https://login.ekstern.dev.nav.no/oauth2/login"
modia_dekorator_scope: "api://dev-gcp.personoversikt.modiacontextholder/.default"
pam_cv_api_scope: "api://dev-gcp.teampam.pam-cv-api-gcp/.default"
adGruppeModiaOppfolging: "554a66fb-fbec-4b92-90c1-0d9c085c362c"
