ingress:
  - "https://cv-veileder.intern.nav.no/min-cv"
tenant: "nav.no"
next_public_environment: "prod"
next_public_telemetry_url: "https://telemetry.nav.no/collect"
base_url: "https://www.ansatt.dev.nav.no/min-cv"
login_url: "https://login.nav.no/oauth2/login"
modia_dekorator_scope: "api://prod-gcp.personoversikt.modiacontextholder/.default"
pam_cv_api_scope: "api://prod-gcp.teampam.pam-cv-api-gcp/.default"
adGruppeModiaOppfolging: "b9bc6348-d25c-450d-85c2-044c0955fbe3"
