apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: cv-veileder
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 8095
  liveness:
    path: /min-cv/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /min-cv/api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: false
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  prometheus:
    enabled: true
    path: /min-cv/api/internal/metrics
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  env:
    - name: PORT
      value: "8095"
    - name: NEXT_PUBLIC_ENVIRONMENT
      value: {{ next_public_environment }}
    - name: BASE_URL
      value: {{ base_url }}
    - name: LOGIN_URL
      value: {{ login_url }}
    - name: PAM_CV_API_BASEURL
      value: http://pam-cv-api-gcp/pam-cv-api/rest
    - name: PAM_CV_API_AUDIENCE
      value: {{ pam_cv_api_audience }}
    - name: PAM_ONTOLOGI_BASEURL
      value: http://pam-ontologi/rest/typeahead
    - name: PAM_EURES_CV_EKSPORT_BASEURL
      value: http://pam-eures-cv-eksport/pam-eures-cv-eksport/samtykke
    - name: PAM_EURES_CV_EKSPORT_AUDIENCE
      value: {{ pam_eures_cv_eksport_audience }}
    - name: NEXT_PUBLIC_TELEMETRY_URL
      value: {{ next_public_telemetry_url }}
  accessPolicy:
    outbound:
      rules:
        - application: modiacontextholder
          namespace: personoversikt
        - application: pam-cv-api-gcp
        - application: pam-ontologi
        - application: pam-eures-cv-eksport
