name: deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".env.local"
      - "docker-compose/*"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - "**"

permissions:
  actions: read
  contents: write
  id-token: write
  packages: write
  security-events: write

jobs:
  create-version-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Lag versjonstag
        run: |
          VERSION_TAG=$(TZ=Europe/Oslo date +"%y.%j.%H%M%S")
          echo "VERSION_TAG=$VERSION_TAG" >> "$GITHUB_ENV"
    outputs:
      version_tag: ${{ env.VERSION_TAG }}
  build-and-deploy-borger:
    if: "(github.ref_name == 'master') || contains(github.event.head_commit.message, 'deploy:dev') || contains(github.ref, 'feature/')"
    needs: [ create-version-tag ]
    uses: navikt/pam-deploy/.github/workflows/deploy-next-js-dev.yml@v7
    with:
      SKIP_DRAFT_RELEASE: ${{ github.ref_name != 'master' }}
      NAIS_VARS: .nais/borger/dev.yml
      NAIS_RESOURCE: .nais/borger/nais.yml
      NPM_BUILD_COMMAND: npm run build:borger
      IMAGE_SUFFIX: cv
      VERSION_TAG: ${{ needs.create-version-tag.outputs.version_tag }}
      NODE_VERSION: 22
    secrets: inherit
  build-and-deploy-veileder:
    if: "(github.ref_name == 'master') || contains(github.event.head_commit.message, 'deploy:dev') || contains(github.ref, 'feature/')"
    needs: [ create-version-tag ]
    uses: navikt/pam-deploy/.github/workflows/deploy-next-js-dev.yml@v7
    with:
      NAIS_VARS: .nais/veileder/dev.yml
      NAIS_RESOURCE: .nais/veileder/nais.yml
      NPM_BUILD_COMMAND: npm run build:veileder
      IMAGE_SUFFIX: cv-veileder
      SKIP_DRAFT_RELEASE: true # Trenger ikke draft for alle appene da de prodsettes samtidig
      CODEQL_ENABLED: false # Trenger ikke CodeQL for alle appene
      VERSION_TAG: ${{ needs.create-version-tag.outputs.version_tag }}
      NODE_VERSION: 22
    secrets: inherit
  build-and-deploy-demo:
    if: "(github.ref_name == 'master') || contains(github.event.head_commit.message, 'deploy:dev') || contains(github.ref, 'feature/')"
    needs: [ create-version-tag ]
    uses: navikt/pam-deploy/.github/workflows/deploy-next-js-dev.yml@v7
    with:
      NAIS_VARS: .nais/demo/dev.yml
      NAIS_RESOURCE: .nais/demo/nais.yml
      NPM_BUILD_COMMAND: npm run build:demo
      IMAGE_SUFFIX: cv-demo
      SKIP_DRAFT_RELEASE: true # Trenger ikke draft for alle appene da de prodsettes samtidig
      CODEQL_ENABLED: false # Trenger ikke CodeQL for alle appene
      VERSION_TAG: ${{ needs.create-version-tag.outputs.version_tag }}
      NODE_VERSION: 22
    secrets: inherit
