name: deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".env.local"
      - "docker-compose.yml"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - "**"

jobs:
  build-and-deploy:
    if: "(github.ref_name == 'master') || contains(github.event.head_commit.message, 'deploy:dev') || contains(github.ref, 'feature/')"
    uses: navikt/pam-deploy/.github/workflows/deploy-next-js-dev.yml@v7
    permissions:
      actions: read
      contents: write
      id-token: write
      packages: write
      security-events: write
    with:
      SKIP_DRAFT_RELEASE: ${{ github.ref_name != 'master' }}
      NAIS_VARS: .nais/dev.yml
    secrets: inherit
  build-and-deploy-veileder:
    if: "contains(github.ref, 'veileder/')"
    uses: navikt/pam-deploy/.github/workflows/deploy-next-js-dev.yml@v7
    permissions:
      actions: read
      contents: write
      id-token: write
      packages: write
      security-events: write
    with:
      SKIP_DRAFT_RELEASE: ${{ github.ref_name != 'master' }}
      NAIS_RESOURCE: .nais/nais-veileder.yml
      NAIS_VARS: .nais/dev-veileder.yml
      NPM_BUILD_COMMAND: npm run build:veileder
    secrets: inherit
