name: deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".env.local"
      - "docker-compose.yml"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - "**"

jobs:
  build-and-deploy:
    if: "(github.ref_name == 'master') || contains(github.event.head_commit.message, 'deploy:dev') || contains(github.ref, 'feature/')"
    uses: navikt/pam-deploy/.github/workflows/deploy-next-js-dev.yml@v7
    permissions:
      actions: read
      contents: write
      id-token: write
      packages: write
      security-events: write
    with:
      SKIP_DRAFT_RELEASE: ${{ github.ref_name != 'master' }}
    secrets: inherit
  setup-dekorator:
    name: Setup dekorator
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
